### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by hirehamir**
I wasn't seeing the GitHub Corner at https://danchitnis.github.io/webgl-plot-examples/vanilla/ after I made the changes in commit b06e39df85e4a7f8dccab6d8e8f71c704e65c5d6, so I think I may have made changes to the wrong `index.html` file.

I'm not sure, but updating this `index.html` file might make the changes appear at https://danchitnis.github.io/webgl-plot-examples/vanilla/.

### CODE REVIEW

**Comment by danchitnis** [comment]
Thanks for this. I have to check if the badge blocks the view of the canvas especially on mobile devices. I will return back to this soon.

**Comment by hirehamir** [comment]
Sounds good! No problem.

**Comment by danchitnis** [comment]
Done! I will apply it to the other pages too. If you are using the examples, then look at the fast-code branch as I am re-writing the examples for a better coding style.

**Comment by hirehamir** [comment]
Alright, sounds good!

**Pull request merged**
